AWSTemplateFormatVersion: "2010-09-09"

Description: Music Charts Real-Time Analytics Infrastructure


Resources:

  # -------------------------
  # S3 Data Lake Bucket
  # -------------------------

  MusicDataLakeBucket:

    Type: AWS::S3::Bucket

    Properties:

      BucketName: music-charts-data-lake



  # -------------------------
  # Kinesis Data Stream
  # -------------------------

  MusicStream:

    Type: AWS::Kinesis::Stream

    Properties:

      Name: music-stream

      StreamModeDetails:

        StreamMode: ON_DEMAND



  # -------------------------
  # DynamoDB Table
  # -------------------------

  MusicEventsTable:

    Type: AWS::DynamoDB::Table

    Properties:

      TableName: music-events

      BillingMode: PAY_PER_REQUEST


      AttributeDefinitions:

        - AttributeName: event_id
          AttributeType: S



      KeySchema:

        - AttributeName: event_id
          KeyType: HASH



Outputs:


  S3BucketName:

    Description: S3 Data Lake Bucket

    Value:

      Ref: MusicDataLakeBucket



  KinesisStreamName:

    Description: Kinesis Stream

    Value:

      Ref: MusicStream



  DynamoDBTableName:

    Description: DynamoDB Table

    Value:

      Ref: MusicEventsTable